/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.IotByLayerKey

/**
 * 
 * @param key 
 * @param ruleId 
 */
data class ActionEventKey (
    val key: IotByLayerKey? = null,
    val ruleId: java.util.UUID? = null
) {

}

