/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


import com.squareup.moshi.Json
/**
 * 
 * @param type 
 * @param params 
 * @param triggerCondition 
 */
data class Action (
    val type: kotlin.String? = null,
    val params: kotlin.Any? = null,
    val triggerCondition: Action.TriggerCondition? = null
) {

    /**
    * 
    * Values: onEnter,onLeave,onEnterAndOnLeave,always
    */
    enum class TriggerCondition(val value: kotlin.String){
    
        @Json(name = "OnEnter") onEnter("OnEnter"),
    
        @Json(name = "OnLeave") onLeave("OnLeave"),
    
        @Json(name = "OnEnterAndOnLeave") onEnterAndOnLeave("OnEnterAndOnLeave"),
    
        @Json(name = "Always") always("Always");
    
    }

}

