/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param id 
 * @param name 
 * @param normalizedName 
 * @param concurrencyStamp 
 */
data class ApplicationRole (
    val id: java.util.UUID? = null,
    val name: kotlin.String? = null,
    val normalizedName: kotlin.String? = null,
    val concurrencyStamp: kotlin.String? = null
) {

}

