/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.IotDataKey
import com.nsimtech.rastersclient.data.Serializer.UUIDSerializer
import kotlinx.serialization.Serializable

/**
 * 
 * @param assetId 
 * @param deviceId 
 */
@Serializable
data class AssetDevice (
    @Serializable(with = UUIDSerializer::class)
    val assetId: java.util.UUID? = null,
    val deviceId: IotDataKey? = null
) {

}

