/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.AssetDevice
import com.nsimtech.rastersclient.data.Organization

/**
 * 
 * @param id 
 * @param name 
 * @param bindings 
 * @param creationDate 
 * @param createdBy 
 * @param organizationId 
 * @param organization 
 * @param assetDevices 
 * @param deviceCount 
 */
data class Asset (
    val id: java.util.UUID? = null,
    val name: kotlin.String? = null,
    val bindings: kotlin.Any? = null,
    val creationDate: java.time.LocalDateTime? = null,
    val createdBy: kotlin.String? = null,
    val organizationId: java.util.UUID? = null,
    val organization: Organization? = null,
    val assetDevices: kotlin.Array<AssetDevice>? = null,
    val deviceCount: kotlin.Int? = null
) {

}

