/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.AssetDevice
import com.nsimtech.rastersclient.data.Organization
import com.nsimtech.rastersclient.data.Serializer.DateSerializer
import com.nsimtech.rastersclient.data.Serializer.UUIDSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
import java.util.*

/**
 * 
 * @param id 
 * @param name 
 * @param bindings 
 * @param creationDate 
 * @param createdBy 
 * @param organizationId 
 * @param organization 
 * @param assetDevices 
 * @param deviceCount 
 */
@Serializable
data class Asset (
    @Serializable(with = UUIDSerializer::class)
    val id: java.util.UUID? = null,
    val name: kotlin.String? = null,
    val bindings: JsonObject? = null,

    @Serializable(with = DateSerializer::class)
    val creationDate: Date? = null,

    val createdBy: kotlin.String? = null,
    @Serializable(with = UUIDSerializer::class)
    val organizationId: java.util.UUID? = null,
    val organization: Organization? = null,
    val assetDevices: kotlin.Array<AssetDevice>? = null,
    val deviceCount: kotlin.Int? = null
) {

}

