/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.HealthStatus

import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param type 
 * @param notifyUri 
 * @param notifyMethod 
 * @param notifySecret 
 * @param hasNotify 
 * @param pollingInterval 
 * @param ttl 
 * @param lastCleanDate 
 * @param lastUpdateDate 
 * @param organizationId 
 * @param healthStatus 
 * @param config 
 * @param mergeStrategy 
 */
data class Connector (
    val name: kotlin.String,
    val type: kotlin.Int,
    val id: java.util.UUID? = null,
    val notifyUri: kotlin.String? = null,
    val notifyMethod: kotlin.String? = null,
    val notifySecret: kotlin.String? = null,
    val hasNotify: kotlin.Boolean? = null,
    val pollingInterval: kotlin.Int? = null,
    val ttl: kotlin.Long? = null,
    val lastCleanDate: String? = null,
    val lastUpdateDate: String? = null,
    val organizationId: java.util.UUID? = null,
    val healthStatus: HealthStatus? = null,
    val config: kotlin.Any? = null,
    val mergeStrategy: Connector.MergeStrategy? = null
) {

    /**
    * 
    * Values: replace,merge
    */
    enum class MergeStrategy(val value: kotlin.String){
    
        @Json(name = "Replace") replace("Replace"),
    
        @Json(name = "Merge") merge("Merge");
    
    }

}

