/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param organizationId 
 * @param name 
 * @param description 
 * @param type 
 * @param notifyUri 
 * @param notifyMethod 
 * @param notifySecret 
 * @param isSystem 
 * @param pollingTime 
 * @param mergeStrategy 
 * @param configTemplate 
 */
data class ConnectorTypes (
    val id: java.util.UUID? = null,
    val organizationId: java.util.UUID? = null,
    val name: kotlin.String? = null,
    val description: kotlin.String? = null,
    val type: kotlin.Int? = null,
    val notifyUri: kotlin.String? = null,
    val notifyMethod: kotlin.String? = null,
    val notifySecret: kotlin.String? = null,
    val isSystem: kotlin.Boolean? = null,
    val pollingTime: kotlin.Int? = null,
    val mergeStrategy: ConnectorTypes.MergeStrategy? = null,
    val configTemplate: kotlin.Any? = null
) {

    /**
    * 
    * Values: replace,merge
    */
    enum class MergeStrategy(val value: kotlin.String){
    
        @Json(name = "Replace") replace("Replace"),
    
        @Json(name = "Merge") merge("Merge");
    
    }

}

