/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param type 
 * @param notifyUri 
 * @param notifyMethod 
 * @param notifySecret 
 * @param pollingInterval 
 * @param ttl 
 * @param config 
 * @param mergeStrategy 
 */
data class ConnectorEntry (
    val name: kotlin.String,
    val type: kotlin.Int,
    val ttl: kotlin.Double,
    val notifyUri: kotlin.String? = null,
    val notifyMethod: kotlin.String? = null,
    val notifySecret: kotlin.String? = null,
    val pollingInterval: kotlin.Int? = null,
    val config: kotlin.Any? = null,
    val mergeStrategy: ConnectorEntry.MergeStrategy? = null
) {

    /**
    * 
    * Values: replace,merge
    */
    enum class MergeStrategy(val value: kotlin.String){
    
        @Json(name = "Replace") replace("Replace"),
    
        @Json(name = "Merge") merge("Merge");
    
    }

}

