/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param mapKey 
 * @param limit 
 * @param filters 
 */
data class EventQueryModel (
    val mapKey: java.util.UUID? = null,
    val limit: kotlin.Int? = null,
    val filters: kotlin.Any? = null
) {

}

