/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Serializer.UUIDSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject


/**
 * 
 * @param mapKey 
 * @param limit 
 * @param filters 
 */
@Serializable
data class EventQueryModel (
    @Serializable(with = UUIDSerializer::class)
    val mapKey: java.util.UUID? = null,
    val limit: kotlin.Int? = null,
    val filters: JsonObject? = null
) {

}

