/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.HeaderType

/**
 * 
 * @param uri 
 * @param method 
 * @param headers 
 */
data class FileLink (
    val uri: kotlin.String? = null,
    val method: kotlin.String? = null,
    val headers: kotlin.Array<HeaderType>? = null
) {

}

