/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param placeId 
 * @param lat 
 * @param lon 
 * @param boundingBox 
 * @param displayName 
 * @param &#x60;class&#x60; 
 * @param type 
 * @param importance 
 */
data class GeocoderResultData (
    val placeId: kotlin.String? = null,
    val lat: kotlin.Float? = null,
    val lon: kotlin.Float? = null,
    val boundingBox: kotlin.Array<kotlin.Float>? = null,
    val displayName: kotlin.String? = null,
    val `class`: kotlin.String? = null,
    val type: kotlin.String? = null,
    val importance: kotlin.Float? = null
) {

}

