/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Serializer.DateSerializer
import kotlinx.serialization.Serializable
import java.util.*


/**
 * 
 * @param isHealthy 
 * @param lastUpdate 
 * @param error 
 */
data class HealthStatus (
    val isHealthy: kotlin.Boolean? = null,

    @Serializable(with = DateSerializer::class)
    val lastUpdate: Date? = null,

    val error: kotlin.String? = null
) {

}

