/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Attachment
import com.nsimtech.rastersclient.data.IotDataKey
import kotlinx.serialization.ContextualSerialization
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * 
 * @param id 
 * @param isFeature 
 * @param type 
 * @param deviceName 
 * @param geometry 
 * @param date 
 * @param &#x60;data&#x60; 
 * @param metadata 
 * @param attachments 
 * @param isShared 
 * @param isLocked 
 * @param bindings 
 */
@Serializable
data class IIotData (
    val id: IotDataKey? = null,
    val isFeature: kotlin.Boolean? = null,
    val type: kotlin.String? = null,
    val deviceName: kotlin.String? = null,
    val geometry: JsonObject? = null,
    val date: String? = null,
    val `data`: JsonObject? = null,
    val metadata: JsonObject? = null,
    @ContextualSerialization
    val attachments: kotlin.Array<Attachment>? = null,
    val isShared: kotlin.Boolean? = null,
    val isLocked: kotlin.Boolean? = null,
    val bindings: JsonObject? = null
) {

}

