/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param id 
 * @param recipient 
 * @param organizationId 
 * @param date 
 * @param roleId 
 * @param role 
 * @param existingUser 
 * @param hasExpired 
 */
data class InvitationOutput (
    val id: java.util.UUID? = null,
    val recipient: kotlin.String? = null,
    val organizationId: java.util.UUID? = null,
    val date: String? = null,
    val roleId: java.util.UUID? = null,
    val role: kotlin.String? = null,
    val existingUser: kotlin.Boolean? = null,
    val hasExpired: kotlin.Boolean? = null
) {

}

