/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.IotDataKey
import com.nsimtech.rastersclient.data.Serializer.UUIDSerializer
import kotlinx.serialization.ContextualSerialization
import kotlinx.serialization.Serializable

/**
 * 
 * @param iotDataKey 
 * @param layerId 
 */
@Serializable
data class IotByLayerKey (
    val iotDataKey: IotDataKey? = null,
    @Serializable(with = UUIDSerializer::class)
    val layerId: java.util.UUID? = null
) {

}

