/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Serializer.DateSerializer
import com.nsimtech.rastersclient.data.Serializer.JsonSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject
import java.util.*

/**
 * 
 * @param id 
 * @param is_feature 
 * @param type 
 * @param device_name 
 * @param geometry 
 * @param date 
 * @param &#x60;data&#x60; 
 * @param bindings 
 */
@Serializable
data class IotData (
    var id: IotDataKey? = null,
    var is_feature: kotlin.Boolean? = null,
    var is_shared: kotlin.Boolean? = null,
    var is_locked: kotlin.Boolean? = null,
    var type: kotlin.String? = null,
    var device_name: kotlin.String? = null,
    var geometry: JsonObject? = null,

    @Serializable(with = DateSerializer::class)
    var date: Date? = null,

    var data: JsonObject? = null,
    var bindings: JsonObject? = null,
    var metadata: JsonObject? = null
) {

}

