/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.fasterxml.jackson.annotation.JsonValue
import com.google.gson.annotations.SerializedName
import com.nsimtech.rastersclient.data.IIotData
import com.nsimtech.rastersclient.data.IotByLayerKey
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject
import org.json.JSONObject

/**
 * 
 * @param &#x60;data&#x60; 
 * @param key 
 * @param text 
 * @param orientation 
 * @param style 
 * @param projectedFields 
 */
data class IotReceived (
    var data: IotData? = null,
    var key: IotByLayerKey? = null,
    var text: kotlin.String? = null,
    var orientation: kotlin.Int? = null,
    var style: Any? = null,
    var projectedFields: JSONObject? = null
) {

}

