/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Serializer.JsonSerializer
import com.nsimtech.rastersclient.data.Serializer.UUIDSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonObject

/**
 * 
 * @param &#x60;data&#x60; 
 * @param key 
 * @param text 
 * @param orientation 
 * @param style 
 * @param projectedFields 
 */
@Serializable
data class IotReceived (
    var data: IotData? = null,
    var key: IotByLayerKey? = null,
    var text: kotlin.String? = null,
    var orientation: kotlin.Int? = null,
    var style: JsonElement? = null,
    var projectedFields: JsonElement? = null
) {

}

