/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.DataSet
import com.nsimtech.rastersclient.data.MapLayer

import com.squareup.moshi.Json
/**
 * 
 * @param name 
 * @param theme 
 * @param type 
 * @param projection 
 * @param size 
 * @param owner 
 * @param creationDate 
 * @param updatedDate 
 * @param description 
 * @param isBaseLayer 
 * @param priority 
 * @param organizationId 
 * @param connectorId 
 * @param mapLayers 
 * @param dataSetId 
 * @param dataSet 
 * @param attributes 
 * @param id 
 */
data class Layer (
    val name: kotlin.String,
    val type: Layer.Type,
    val dataSetId: java.util.UUID,
    val theme: kotlin.String? = null,
    val projection: kotlin.String? = null,
    val size: kotlin.Double? = null,
    val owner: kotlin.String? = null,
    val creationDate: String? = null,
    val updatedDate: String? = null,
    val description: kotlin.String? = null,
    val isBaseLayer: kotlin.Boolean? = null,
    val priority: kotlin.Int? = null,
    val organizationId: java.util.UUID? = null,
    val connectorId: java.util.UUID? = null,
    val mapLayers: kotlin.Array<MapLayer>? = null,
    val dataSet: DataSet? = null,
    val attributes: kotlin.String? = null,
    val id: java.util.UUID? = null
) {

    /**
    * 
    * Values: raster,vector,`annotation`,collect,iot
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "Raster") raster("Raster"),
    
        @Json(name = "Vector") vector("Vector"),
    
        @Json(name = "Annotation") `annotation`("Annotation"),
    
        @Json(name = "Collect") collect("Collect"),
    
        @Json(name = "Iot") iot("Iot");
    
    }

}

