/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param mapKey 
 * @param organizationId 
 * @param name 
 * @param creationDate 
 * @param updatedDate 
 * @param isShared 
 * @param layerCount 
 * @param description 
 * @param mapLayers 
 */
data class Map (
    val name: kotlin.String,
    val mapKey: java.util.UUID? = null,
    val organizationId: java.util.UUID? = null,
    val creationDate: String? = null,
    val updatedDate: String? = null,
    val isShared: kotlin.Boolean? = null,
    val layerCount: kotlin.Int? = null,
    val description: kotlin.String? = null,
    val mapLayers: kotlin.Array<MapLayer>? = null
) {

}

