/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param mapId 
 * @param layerId 
 */
data class MapLayer (
    val mapId: java.util.UUID? = null,
    val layerId: java.util.UUID? = null
) {

}

