/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


import com.squareup.moshi.Json
/**
 * 
 * @param id 
 * @param name 
 * @param token 
 * @param mapKey 
 * @param scopes 
 * @param createdDate 
 * @param type 
 */
data class MapTokenOutput (
    val id: java.util.UUID? = null,
    val name: kotlin.String? = null,
    val token: kotlin.String? = null,
    val mapKey: java.util.UUID? = null,
    val scopes: kotlin.Array<kotlin.String>? = null,
    val createdDate: String? = null,
    val type: MapTokenOutput.Type? = null
) {

    /**
    * 
    * Values: classic,urlShare,facebookShare
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "classic") classic("classic"),
    
        @Json(name = "url_share") urlShare("url_share"),
    
        @Json(name = "facebook_share") facebookShare("facebook_share");
    
    }

}

