/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param role 
 * @param roleId 
 * @param email 
 * @param firstname 
 * @param lastname 
 * @param userId 
 * @param isOwner 
 */
data class Member (
    val role: kotlin.String? = null,
    val roleId: java.util.UUID? = null,
    val email: kotlin.String? = null,
    val firstname: kotlin.String? = null,
    val lastname: kotlin.String? = null,
    val userId: java.util.UUID? = null,
    val isOwner: kotlin.Boolean? = null
) {

}

