/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Address
import com.nsimtech.rastersclient.data.Contact

/**
 * 
 * @param name 
 * @param address 
 * @param contact 
 */
data class OrganizationEntry (
    val name: kotlin.String,
    val address: Address? = null,
    val contact: Contact? = null
) {

}

