/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Address
import com.nsimtech.rastersclient.data.Contact
import com.nsimtech.rastersclient.data.Serializer.UUIDSerializer
import kotlinx.serialization.ContextualSerialization
import kotlinx.serialization.Serializable

/**
 * 
 * @param id 
 * @param name 
 * @param address 
 * @param userId 
 * @param contact 
 * @param mapDemoId 
 */
@Serializable
data class Organization (
    val name: kotlin.String,
    @Serializable(with = UUIDSerializer::class)
    val id: java.util.UUID? = null,
    @ContextualSerialization
    val address: Address? = null,
    @Serializable(with = UUIDSerializer::class)
    val userId: java.util.UUID? = null,
    val contact: Contact? = null,
    val mapDemoId: kotlin.String? = null
) {

}

