/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.RuleActionEvent

/**
 * 
 * @param items 
 * @param itemsCount 
 * @param hasMore 
 * @param limit 
 * @param skip 
 * @param total 
 */
data class QueryResultLeftSquareBracketRuleActionEventRightSquareBracket (
    val items: kotlin.Array<RuleActionEvent>? = null,
    val itemsCount: kotlin.Int? = null,
    val hasMore: kotlin.Boolean? = null,
    val limit: kotlin.Int? = null,
    val skip: kotlin.Int? = null,
    val total: kotlin.Long? = null
) {

}

