/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import kotlinx.serialization.Serializable


/**
 * 
 * @param items 
 * @param limit 
 * @param skip 
 * @param total 
 */
@Serializable
data class QueryResult<T> (
    val items: kotlin.Array<T>? = null,
    val limit: kotlin.Int? = null,
    val skip: kotlin.Int? = null,
    val total: kotlin.Long? = null
) {

}

