/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


import com.squareup.moshi.Json
/**
 * 
 * @param type 
 * @param redirectUri 
 * @param email 
 */
data class ResendEmailModel (
    val type: ResendEmailModel.Type,
    val redirectUri: kotlin.String,
    val email: kotlin.String
) {

    /**
    * 
    * Values: welcome,confirmAccount,invitation,resetPassword
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "Welcome") welcome("Welcome"),
    
        @Json(name = "ConfirmAccount") confirmAccount("ConfirmAccount"),
    
        @Json(name = "Invitation") invitation("Invitation"),
    
        @Json(name = "ResetPassword") resetPassword("ResetPassword");
    
    }

}

