/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param lat 
 * @param lon 
 */
data class ReverseGeocoderEntry (
    val lat: kotlin.Double? = null,
    val lon: kotlin.Double? = null
) {

}

