/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param placeId 
 * @param lat 
 * @param lon 
 * @param displayName 
 * @param address 
 */
data class ReverseGeocoderData (
    val placeId: kotlin.String? = null,
    val lat: kotlin.Float? = null,
    val lon: kotlin.Float? = null,
    val displayName: kotlin.String? = null,
    val address: kotlin.Any? = null
) {

}

