/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Action

/**
 * 
 * @param id 
 * @param layerId 
 * @param organizationId 
 * @param enabled 
 * @param name 
 * @param description 
 * @param priority 
 * @param deviceIds 
 * @param condition 
 * @param actions 
 * @param relatedIds 
 */
data class Rule (
    val id: java.util.UUID,
    val layerId: java.util.UUID? = null,
    val organizationId: java.util.UUID? = null,
    val enabled: kotlin.Boolean? = null,
    val name: kotlin.String? = null,
    val description: kotlin.String? = null,
    val priority: kotlin.Int? = null,
    val deviceIds: kotlin.Array<kotlin.String>? = null,
    val condition: kotlin.Any? = null,
    val actions: kotlin.Array<Action>? = null,
    val relatedIds: kotlin.Array<java.util.UUID>? = null
) {

}

