/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Action
import com.nsimtech.rastersclient.data.ActionEventKey
import com.nsimtech.rastersclient.data.IotData
import com.nsimtech.rastersclient.data.Rule
import com.nsimtech.rastersclient.data.RuleExecutionState

import com.squareup.moshi.Json
/**
 * 
 * @param _id 
 * @param id 
 * @param rule 
 * @param date 
 * @param &#x60;data&#x60; 
 * @param action 
 * @param lastState 
 * @param state 
 * @param duration 
 * @param trigger 
 */
data class RuleActionEvent (
    val _id: kotlin.Any? = null,
    val id: ActionEventKey? = null,
    val rule: Rule? = null,
    val date: String? = null,
    val `data`: IotData? = null,
    val action: Action? = null,
    val lastState: RuleExecutionState? = null,
    val state: RuleExecutionState? = null,
    val duration: kotlin.Long? = null,
    val trigger: RuleActionEvent.Trigger? = null
) {

    /**
    * 
    * Values: onEnter,onLeave,onEnterAndOnLeave,always
    */
    enum class Trigger(val value: kotlin.String){
    
        @Json(name = "OnEnter") onEnter("OnEnter"),
    
        @Json(name = "OnLeave") onLeave("OnLeave"),
    
        @Json(name = "OnEnterAndOnLeave") onEnterAndOnLeave("OnEnterAndOnLeave"),
    
        @Json(name = "Always") always("Always");
    
    }

}

