/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import kotlinx.serialization.Serializable


/**
 * 
 * @param phoneNumber 
 * @param email 
 */
@Serializable
data class Specificity (
    var particularities: List<Particularity>? = null
) {

}

