/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data


/**
 * 
 * @param email 
 * @param password 
 * @param firstname 
 * @param lastname 
 * @param language 
 * @param timezone 
 * @param redirectUri 
 */
data class UserRegistration (
    val email: kotlin.String,
    val password: kotlin.String,
    val language: kotlin.String,
    val timezone: kotlin.String,
    val redirectUri: kotlin.String,
    val firstname: kotlin.String? = null,
    val lastname: kotlin.String? = null
) {

}

