/**
* Rasters API
* No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
*
* OpenAPI spec version: v2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package com.nsimtech.rastersclient.data

import com.nsimtech.rastersclient.data.Address

/**
 * 
 * @param firstname 
 * @param lastname 
 * @param address 
 * @param culture 
 * @param timezone 
 */
data class UserEntry (
    val address: Address,
    val firstname: kotlin.String? = null,
    val lastname: kotlin.String? = null,
    val culture: kotlin.String? = null,
    val timezone: kotlin.String? = null
) {

}

